version: '3'

services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lofi
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
        - "3306:3306"
    